const ROUTES_DATA = [
  {
    origin: "KDI",
    destination: "UPG",
    airline: "Lion Air",
    flight: "JT-991",
    days: "Setiap Hari",
    time: "07:00 WITA",
    status: "Aktif",
    nexttrip: "CGK",
    image: "images/lion-air.jpg",
    checkin: "https://www.bookcabin.com/"
  },
  {
    origin: "KDI",
    destination: "UPG",
    airline: "Super Air Jet",
    flight: "IU-589",
    days: "Setiap Hari",
    time: "07:15 WITA",
    status: "Tutup",
    closedDate: "14 September 2024",
    image: "images/super-air-jet.jpg",
    checkin: "https://www.bookcabin.com/"
  },
  {
    origin: "KDI",
    destination: "UPG",
    airline: "Citilink",
    flight: "QG-333",
    days: "Setiap Hari",
    time: "8:00 WITA",
    status: "Tutup",
    image: "images/citilink.jpg",
    checkin: "https://m-member.citilink.co.id/app/checkin"
  },
  {
    origin: "KDI",
    destination: "CGK",
    airline: "Batik Air",
    flight: "ID-6723",
    days: "Setiap Hari",
    time: "08:00 WITA",
    status: "Aktif",
    image: "images/batik-air.jpg",
    checkin: "https://www.bookcabin.com/"
  },
  {
    origin: "KDI",
    destination: "UPG",
    airline: "Garuda Indonesia",
    flight: "GA-604",
    days: "Setiap Hari",
    time: "08:40 WITA",
    status: "Aktif",
    nexttrip: "CGK",
    image: "images/garuda-indonesia.jpg",
    checkin: "https://www.garuda-indonesia.com/id/id"
  },
  {
    origin: "KDI",
    destination: "UPG",
    airline: "Lion Air",
    flight: "JT-987",
    days: "Setiap Hari",
    time: "08:45 WITA",
    status: "Aktif",
    image: "images/lion-air.jpg",
    checkin: "https://www.bookcabin.com/"
  },
  {
    origin: "KDI",
    destination: "WNI",
    airline: "WIngs Air",
    flight: "IW-1336",
    days: "Setiap Hari",
    time: "09:25 WITA",
    closedDate: "27 Mei 2025",
    status: "Tutup",
    image: "images/wings-air.jpg",
    checkin: "https://www.bookcabin.com/"
  },
  {
    origin: "KDI",
    destination: "UPG",
    airline: "Air Asia",
    flight: "QZ-738",
    days: "Setiap Hari",
    time: "09:35 WITA",
    status: "Akan Datang",
    startflight: "7 Maret 2026",
    nexttrip: "PLW",
    image: "images/air-asia.jpg",
    checkin: "https://www.airasia.com/check-in/v2/en/gb"
  },
  {
    origin: "KDI",
    destination: "WNI",
    airline: "Fly Jaya",
    flight: "KS-320",
    days: "Selasa dan Jumat",
    time: "09:50 WITA",
    status: "Aktif",
    image: "images/fly-jaya.jpg",
    checkin: "https://reservation.flyjaya.com/en/WebCheckin"
  },
  {
    origin: "KDI",
    destination: "UPG",
    airline: "Batik Air",
    flight: "ID-6750",
    days: "Setiap Hari",
    time: "10:15 WITA",
    status: "Aktif",
    image: "images/batik-air.jpg",
    checkin: "https://www.bookcabin.com/"
  },
  {
    origin: "KDI",
    destination: "APD",
    airline: "Susi AIr",
    flight: "SQS-XXX",
    days: "Senin, Rabu dan Jumat",
    time: "10:20 WITA",
    status: "Tutup",
    image: "images/susi-air.jpg",
    checkin: "https://pss01.nieve.id/webcheckin/?_gl=1*88o5ma*_gcl_au*MTg4NzE4OTAxLjE3Njg4MjIxNTk."
  },
  {
    origin: "KDI",
    destination: "CGK",
    airline: "Pelita Air",
    flight: "IP-810",
    days: "Setiap Hari",
    time: "10:25 WITA",
    status: "Aktif",
    image: "images/pelita-air.jpg",
    checkin: "https://pss01.nieve.id/webcheckin/?_gl=1*88o5ma*_gcl_au*MTg4NzE4OTAxLjE3Njg4MjIxNTk."
  },
  {
    origin: "KDI",
    destination: "UPG",
    airline: "Super Air Jet",
    flight: "IU-585",
    days: "Setiap Hari",
    time: "11:20 WITA",
    status: "Tutup",
    closedDate: "14 September 2024",
    nexttrip: "SUB",
    image: "images/super-air-jet.jpg",
    checkin: "https://www.bookcabin.com/"
  },
  {
    origin: "KDI",
    destination: "MOH",
    airline: "WIngs Air",
    flight: "IW-1338",
    days: "Setiap Hari",
    time: "12:30 WITA",
    status: "Tutup",
    closedDate: "27 Mei 2026",
    nexttrip: "UPG",
    image: "images/wings-air.jpg",
    checkin: "https://www.bookcabin.com/"
  },
  {
    origin: "KDI",
    destination: "APD",
    airline: "Fly Jaya",
    flight: "KS-311",
    days: "Selasa dan Jumat",
    time: "12:45 WITA",
    status: "Aktif",
    nexttrip: "UPG",
    image: "images/fly-jaya.jpg",
    checkin: "https://reservation.flyjaya.com/en/WebCheckin"
  },
  {
    origin: "KDI",
    destination: "BUW",
    airline: "WIngs Air",
    flight: "IW-1319",
    days: "Senin dan Jumat",
    time: "13:10 WITA",
    status: "Tutup",
    image: "images/wings-air.jpg",
    checkin: "https://www.bookcabin.com/"
  },
  {
    origin: "KDI",
    destination: "UPG",
    airline: "Lion Air",
    flight: "JT-993",
    days: "Setiap Hari",
    time: "14:30 WITA",
    status: "Aktif",
    nexttrip: "CGK",
    image: "images/lion-air.jpg",
    checkin: "https://www.bookcabin.com/"
  },
  {
    origin: "KDI",
    destination: "UPG",
    airline: "Super Air Jet",
    flight: "IU-589",
    days: "Setiap Hari",
    time: "14:40 WITA",
    status: "Tutup",
    closedDate: "14 September 2024",
    nexttrip: "SUB",
    image: "images/super-air-jet.jpg",
    checkin: "https://www.bookcabin.com/"
  },
  {
    origin: "KDI",
    destination: "UPG",
    airline: "Lion Air",
    flight: "JT-997",
    days: "Setiap Hari",
    time: "15:35 WITA",
    status: "Aktif",
    nexttrip: "SUB",
    image: "images/lion-air.jpg",
    checkin: "https://www.bookcabin.com/"
  },
  {
    origin: "KDI",
    destination: "CGK",
    airline: "Batik Air",
    flight: "ID-6725",
    days: "Setiap Hari",
    time: "15:40 WITA",
    status: "Tutup",
    closedDate: "10 Juli 2024",
    image: "images/batik-air.jpg",
    checkin: "https://www.bookcabin.com/"
  },
  {
    origin: "KDI",
    destination: "SUB",
    airline: "Lion Air",
    flight: "JT-723",
    days: "Senin, Rabu, Jumat, Minggu",
    time: "16:05 WITA",
    status: "Aktif Kembali",
    aktifback: "23 Januari 2026",
    image: "images/lion-air.jpg",
    checkin: "https://www.bookcabin.com/"
  },
  {
    origin: "KDI",
    destination: "SUB",
    airline: "Super Air Jet",
    flight: "IU-561",
    days: "Senin, Rabu, Jumat, Minggu",
    time: "16:05 WITA",
    status: "Aktif",
    image: "images/super-air-jet.jpg",
    checkin: "https://www.bookcabin.com/"
  },
  {
    origin: "KDI",
    destination: "CGK",
    airline: "Super Air Jet",
    flight: "IU-259",
    days: "Setiap Hari",
    time: "17:20 WITA",
    status: "Aktif",
    image: "images/super-air-jet.jpg",
    checkin: "https://www.bookcabin.com/"
  },
  {
    origin: "KDI",
    destination: "CGK",
    airline: "Citilink",
    flight: "QG-331",
    days: "Setiap Hari",
    time: "18:00 WITA",
    status: "Aktif",
    image: "images/citilink.jpg",
    checkin: "https://m-member.citilink.co.id/app/checkin"
  },
  {
    origin: "KDI",
    destination: "CGK",
    airline: "Batik Air",
    flight: "ID-6727",
    days: "Setiap Hari",
    time: "18:30 WITA",
    status: "Tutup",
    closedDate: "24 Juli 2024",
    image: "images/batik-air.jpg",
    checkin: "https://www.bookcabin.com/"
  },
  {
    origin: "KDI",
    destination: "UPG",
    airline: "Air Asia",
    flight: "QZ-733",
    days: "Setiap Hari",
    time: "18:40 WITA",
    status: "Akan Datang",
    startflight: "7 Maret 2026",
    nexttrip: "SUB",
    image: "images/air-asia.jpg",
    checkin: "https://www.airasia.com/check-in/v2/en/gb"
  },
];